story_generators:
- name: ssg_pagila.rental_story
  num_stories_per_pass: 30
story_generators_module: ssg_pagila
tables:
  actor:
    row_generators:
    - columns_assigned: first_name
      name: generic.person.first_name
    - columns_assigned: last_name
      name: generic.person.last_name
  address:
    num_rows_per_pass: 1
    row_generators:
    - columns_assigned: fulltext
      name: generic.text.text
    vocabulary_columns:
    - rating
    - rental_duration
    - rental_rate
    - replacement_cost
  category:
    vocabulary_table: true
  city:
    vocabulary_table: true
  country:
    vocabulary_table: true
  customer:
    row_generators:
    - columns_assigned: email
      name: generic.person.email
    - columns_assigned: first_name
      name: generic.person.first_name
    - columns_assigned: last_name
      name: generic.person.last_name
    vocabulary_columns:
    - active
  language:
    vocabulary_table: true
  payment:
    vocabulary_columns:
    - amount
  payment_p2022_01:
    ignore: true
  payment_p2022_02:
    ignore: true
  payment_p2022_03:
    ignore: true
  payment_p2022_04:
    ignore: true
  payment_p2022_05:
    ignore: true
  payment_p2022_06:
    ignore: true
  payment_p2022_07:
    ignore: true
