"""This file was auto-generated by datafaker but can be edited manually."""
from mimesis import Generic, Numeric, Person
from mimesis.locales import Locale
import sqlalchemy
import sys
from datafaker.base import FileUploader, TableGenerator, ColumnPresence
from datafaker.providers import DistributionProvider

generic = Generic(locale=Locale.EN_GB)
numeric = Numeric()
person = Person()
dist_gen = DistributionProvider()
column_presence = ColumnPresence()

sys.path.append("")

from datafaker.providers import (
    BytesProvider,
    ColumnValueProvider,
    DistributionProvider,
    NullProvider,
    SQLGroupByProvider,
    TimedeltaProvider,
    TimespanProvider,
    WeightedBooleanProvider,
)

generic.add_provider(BytesProvider)
generic.add_provider(ColumnValueProvider)
generic.add_provider(DistributionProvider)
generic.add_provider(NullProvider)
generic.add_provider(SQLGroupByProvider)
generic.add_provider(TimedeltaProvider)
generic.add_provider(TimespanProvider)
generic.add_provider(WeightedBooleanProvider)


import yaml

with open("src-stats.yaml", "r", encoding="utf-8") as f:
    SRC_STATS = yaml.unsafe_load(f)


class PersonGenerator(TableGenerator):
    num_rows_per_pass = 1

    def __init__(self):
        self.initialized = False

    def __call__(self, dst_db_conn, metadata):
        if not self.initialized:
            self.initialized = True
        result = {}
        columns_to_generate = set(
            {
                "ethnicity_concept_id",
                "year_of_birth",
                "gender_concept_id",
                "race_concept_id",
            }
        )
        while columns_to_generate:
            if "ethnicity_concept_id" in columns_to_generate:
                result["ethnicity_concept_id"] = dist_gen.weighted_choice(
                    a=SRC_STATS["auto__person__ethnicity_concept_id"]["results"]
                )
            if "gender_concept_id" in columns_to_generate:
                result["gender_concept_id"] = dist_gen.weighted_choice(
                    a=SRC_STATS["auto__person__gender_concept_id"]["results"]
                )
            if "race_concept_id" in columns_to_generate:
                result["race_concept_id"] = dist_gen.weighted_choice(
                    a=SRC_STATS["auto__person__race_concept_id"]["results"]
                )
            if "year_of_birth" in columns_to_generate:
                result["year_of_birth"] = dist_gen.weighted_choice(
                    a=SRC_STATS["auto__person__year_of_birth"]["results"]
                )
            columns_to_generate = set()
        return result


table_generator_dict = {
    "person": PersonGenerator(),
}


story_generator_list = []
