src-stats:
- comments:
  - All the values and their counts that appear in column ethnicity_concept_id of
    table person
  name: auto__person__ethnicity_concept_id
  query: "SELECT _counted.value, _counted.count \nFROM (SELECT \"ethnicity_concept_id\"\
    \ AS value, count(\"ethnicity_concept_id\") AS count \nFROM mimic.person \nWHERE\
    \ \"ethnicity_concept_id\" IS NOT NULL GROUP BY \"ethnicity_concept_id\") AS _counted\
    \ ORDER BY _counted.count DESC"
- comments:
  - All the values and their counts that appear in column gender_concept_id of table
    person
  name: auto__person__gender_concept_id
  query: "SELECT _counted.value, _counted.count \nFROM (SELECT \"gender_concept_id\"\
    \ AS value, count(\"gender_concept_id\") AS count \nFROM mimic.person \nWHERE\
    \ \"gender_concept_id\" IS NOT NULL GROUP BY \"gender_concept_id\") AS _counted\
    \ ORDER BY _counted.count DESC"
- comments:
  - All the values and their counts that appear in column race_concept_id of table
    person
  name: auto__person__race_concept_id
  query: "SELECT _counted.value, _counted.count \nFROM (SELECT \"race_concept_id\"\
    \ AS value, count(\"race_concept_id\") AS count \nFROM mimic.person \nWHERE \"\
    race_concept_id\" IS NOT NULL GROUP BY \"race_concept_id\") AS _counted ORDER\
    \ BY _counted.count DESC"
- comments:
  - All the values and their counts that appear in column year_of_birth of table person
  name: auto__person__year_of_birth
  query: "SELECT _counted.value, _counted.count \nFROM (SELECT \"year_of_birth\" AS\
    \ value, count(\"year_of_birth\") AS count \nFROM mimic.person \nWHERE \"year_of_birth\"\
    \ IS NOT NULL GROUP BY \"year_of_birth\") AS _counted ORDER BY _counted.count\
    \ DESC"
tables:
  concept:
    ignore: false
    vocabulary_table: true
  person:
    num_rows_per_pass: 1
    row_generators:
    - columns_assigned:
      - ethnicity_concept_id
      kwargs:
        a: SRC_STATS["auto__person__ethnicity_concept_id"]["results"]
      name: dist_gen.weighted_choice
    - columns_assigned:
      - gender_concept_id
      kwargs:
        a: SRC_STATS["auto__person__gender_concept_id"]["results"]
      name: dist_gen.weighted_choice
    - columns_assigned:
      - race_concept_id
      kwargs:
        a: SRC_STATS["auto__person__race_concept_id"]["results"]
      name: dist_gen.weighted_choice
    - columns_assigned:
      - year_of_birth
      kwargs:
        a: SRC_STATS["auto__person__year_of_birth"]["results"]
      name: dist_gen.weighted_choice
