"""This file was auto-generated by datafaker but can be edited manually."""
from mimesis import Generic, Numeric, Person
from mimesis.locales import Locale
import sqlalchemy
import sys
from datafaker.base import FileUploader, TableGenerator, ColumnPresence
from datafaker.providers import DistributionProvider

generic = Generic(locale=Locale.EN_GB)
numeric = Numeric()
person = Person()
dist_gen = DistributionProvider()
column_presence = ColumnPresence()

sys.path.append("")

from datafaker.providers import (
    BytesProvider,
    ColumnValueProvider,
    DistributionProvider,
    NullProvider,
    SQLGroupByProvider,
    TimedeltaProvider,
    TimespanProvider,
    WeightedBooleanProvider,
)

generic.add_provider(BytesProvider)
generic.add_provider(ColumnValueProvider)
generic.add_provider(DistributionProvider)
generic.add_provider(NullProvider)
generic.add_provider(SQLGroupByProvider)
generic.add_provider(TimedeltaProvider)
generic.add_provider(TimespanProvider)
generic.add_provider(WeightedBooleanProvider)


class PersonGenerator(TableGenerator):
    num_rows_per_pass = 10

    def __init__(self):
        self.initialized = False

    def __call__(self, dst_db_conn, metadata):
        if not self.initialized:
            self.initialized = True
        result = {}
        columns_to_generate = set(
            {
                "birth_datetime",
                "ethnicity_source_value",
                "ethnicity_source_concept_id",
                "ethnicity_concept_id",
                "person_source_value",
                "race_concept_id",
                "month_of_birth",
                "race_source_value",
                "gender_source_value",
                "day_of_birth",
                "gender_concept_id",
                "race_source_concept_id",
                "gender_source_concept_id",
                "year_of_birth",
            }
        )
        while columns_to_generate:
            if "birth_datetime" in columns_to_generate:
                result["birth_datetime"] = generic.datetime.datetime()
            if "day_of_birth" in columns_to_generate:
                result["day_of_birth"] = generic.numeric.integer_number()
            if "ethnicity_concept_id" in columns_to_generate:
                result[
                    "ethnicity_concept_id"
                ] = generic.column_value_provider.column_value(
                    dst_db_conn, metadata.tables["concept"], "concept_id"
                )
            if "ethnicity_source_concept_id" in columns_to_generate:
                result[
                    "ethnicity_source_concept_id"
                ] = generic.column_value_provider.column_value(
                    dst_db_conn, metadata.tables["concept"], "concept_id"
                )
            if "ethnicity_source_value" in columns_to_generate:
                result["ethnicity_source_value"] = generic.person.password(length=50)
            if "gender_concept_id" in columns_to_generate:
                result[
                    "gender_concept_id"
                ] = generic.column_value_provider.column_value(
                    dst_db_conn, metadata.tables["concept"], "concept_id"
                )
            if "gender_source_concept_id" in columns_to_generate:
                result[
                    "gender_source_concept_id"
                ] = generic.column_value_provider.column_value(
                    dst_db_conn, metadata.tables["concept"], "concept_id"
                )
            if "gender_source_value" in columns_to_generate:
                result["gender_source_value"] = generic.person.password(length=50)
            if "month_of_birth" in columns_to_generate:
                result["month_of_birth"] = generic.numeric.integer_number()
            if "person_source_value" in columns_to_generate:
                result["person_source_value"] = generic.person.password(length=50)
            if "race_concept_id" in columns_to_generate:
                result["race_concept_id"] = generic.column_value_provider.column_value(
                    dst_db_conn, metadata.tables["concept"], "concept_id"
                )
            if "race_source_concept_id" in columns_to_generate:
                result[
                    "race_source_concept_id"
                ] = generic.column_value_provider.column_value(
                    dst_db_conn, metadata.tables["concept"], "concept_id"
                )
            if "race_source_value" in columns_to_generate:
                result["race_source_value"] = generic.person.password(length=50)
            if "year_of_birth" in columns_to_generate:
                result["year_of_birth"] = generic.numeric.integer_number()
            columns_to_generate = set()
        return result


table_generator_dict = {
    "person": PersonGenerator(),
}


story_generator_list = []
