---
name: unit test action
on:
  pull_request:
  # Run on merge to main because caches are inherited from parent branches
  push:
    branches:
      - main
env:
  # This should be the default but we'll be explicit
  PYTHON_VERSION: "3.10"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start PostgreSQL
        shell: bash
        run: |
          sudo systemctl start postgresql.service
      - name: Run tests
        shell: bash
        run: |
          python -m unittest
