---
name: unit test action
on:
  pull_request:
  # Run on merge to main because caches are inherited from parent branches
  push:
    branches:
      - main
env:
  # This should be the default but we'll be explicit
  PYTHON_VERSION: "3.10"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start PostgreSQL
        shell: bash
        run: |
          sudo systemctl start postgresql.service
      - name: Install poetry
        shell: bash
        run: |
          sudo apt install python3-poetry
      - name: Configure poetry
        shell: bash
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Install dependencies
        shell: bash
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: |
          python -m poetry install --all-extras
      - name: Run tests
        shell: bash
        run: |
          poetry run python -m unittest
